# Generated by Django 3.2 on 2021-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('date_start', models.DateTimeField(verbose_name='Дата начала курса')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания курса')),
                ('amount_lecture', models.PositiveSmallIntegerField(verbose_name='Количество лекций')),
            ],
        ),
    ]
